name: plunk
description: Dart and Flutter REST API client library for the Plunk email platform for SaaS. Visit useplunk.com to create an account.
version: 2.0.2
homepage: https://useplunk.com
repository: https://github.com/dartfoundry/plunk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  intl: ^0.20.1
  logging: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - api
  - client
  - rest
  - email
  - saas
