name: plunk
description: REST client for Plunk email platform for SaaS
version: 1.0.0
homepage: https://useplunk.com
repository: https://pocketbusiness.dev

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  rest_client: ^2.2.1+11

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
