name: plunk
description: REST client for Plunk email platform for SaaS
version: 1.0.0
homepage: https://useplunk.com
repository: https://github.com/pocket-business/plunk

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  rest_client: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - api
  - client
  - rest
  - dart
  - flutter
  - email
  - marketing
  - transactional
  - saas
  - plunk
